### ISSUE TITLE
Neovim - reparation

### ISSUE THREAD

**Issue by Breizil29** [Flo-Slv/Dotfiles#1]
Salut Flo, je suis tes videos sur neovim et tous fonctionne parfaitement.
Mon probleme est que quand je lance vim ou nvim j'ai des lignes disgracieuses qui apparaissent :

> Error detected while processing /usr/share/vim/vimfiles/plugin/AlignMapsPlugin.vim[172]..function AlignMaps#MakeMap:
line    8:
E227: mapping already exists for tt
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.11/site-packages/powerline/vim.py", line 15, in <module>
    from powerline.bindings.vim import vim_get_func, vim_getvar, get_vim_encoding, python_to_vim
  File "/usr/lib/python3.11/site-packages/powerline/bindings/vim/__init__.py", line 44, in <module>
    vim_encoding = get_vim_encoding()
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/powerline/bindings/vim/__init__.py", line 25, in get_vim_encoding
    return vim.options['encoding'].decode('ascii') or 'ascii'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing /usr/share/vim/vimfiles/plugin/powerline.vim[169]../usr/share/vim/vimfiles/plugin/powerline.vim[157]..function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):^@Traceback (most recent call last):^@  File "<string>", line 53, in <module>^@  File "<string>", line 40, in powerline_tr
oubleshoot^@  File "/usr/lib/python3.11/site-packages/powerline/lint/__init__.py", line 12, in <module>^@    from powerline.segments.vim import vim_modes^@  File "/usr/lib/python3.11/site-p
ackages/powerline/segments/vim/__init__.py", line 16, in <module>^@    from powerline.bindings.vim import (vim_get_func, getbufvar, vim_getbufoption,^@  File "/usr/lib/python3.11/site-packa
ges/powerline/bindings/vim/__init__.py", line 44, in <module>^@    vim_encoding = get_vim_encoding()^@                   ^^^^^^^^^^^^^^^^^^^@  File "/usr/lib/python3.11/site-packages/powerl
ine/bindings/vim/__init__.py", line 25, in get_vim_encoding^@    return vim.options['encoding'].decode('ascii') or 'ascii'^@           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^@AttributeError: 'str'
object has no attribute 'decode'
Press ENTER or type command to continue

J'aimerais ton avis

**Comment by Breizil29** [comment]
Salut Flo, tu peux supprimer l'issue stp je ne la trouve pas pertinente.
J'ai résolu le pb en désinstallant nvim et en le réinstallant à ta façon en le build.
